### PR TITLE
Fix typo in HUD

### PR DESCRIPTION
**Pull request by rndtrash**

### CODE REVIEW

**Review by Fedcomp — CHANGES_REQUESTED** [review]
I think we need to do something with commit name

**Comment by rndtrash** [comment]
> I think we need to do something with commit name

OK, I'll try to rename it, though tbh it's too much effort for a Hacktober-tier contribution 😆

**Comment by rndtrash** [comment]
Oh no, screenshot has a typo too!
Screenshot

**Comment by Fedcomp** [comment]
@garrynewman screenshot still have that typo by the way. Sorry for ping.

**Pull request merged**
